using Newtonsoft.Json;
using System;

namespace Api.Models
{
    public class SimpressAccountValue
    {
        [JsonProperty("@odata.etag")]
        public string OdataEtag { get; set; }
        public int bz_conta_prioritaria { get; set; }
        public string _sim_estagiodoprocesso_value { get; set; }
        public int address2_addresstypecode { get; set; }
        public int sim_faturamento_mobile_acum_state { get; set; }
        public int sim_faturamento_mps_acum_state { get; set; }
        public bool merged { get; set; }
        public double sim_total_equipamentos_base { get; set; }
        public bool new_centralizado { get; set; }
        public DateTime sim_qtd_oporunidades_date { get; set; }
        public double exchangerate { get; set; }
        public double sim_faturamento_mps_acum { get; set; }
        public int sim_qtd_oportunidade_ganhas_state { get; set; }
        public int sim_faturamento_inov_acum_state { get; set; }
        public string name { get; set; }
        public string _owningbusinessunit_value { get; set; }
        public int address2_shippingmethodcode { get; set; }
        public int opendeals { get; set; }
        public double sim_faturamento_inov_acum_base { get; set; }
        public DateTime modifiedon { get; set; }
        public int sim_total_contratos { get; set; }
        public string _owninguser_value { get; set; }
        public int sim_qtd_equip_state { get; set; }
        public int statecode { get; set; }
        public int sim_qtd_oporunidades { get; set; }
        public int openrevenue_state { get; set; }
        public int sim_qtd_equip { get; set; }
        public bool donotpostalmail { get; set; }
        public int accountratingcode { get; set; }
        public bool marketingonly { get; set; }
        public bool donotphone { get; set; }
        public int preferredcontactmethodcode { get; set; }
        public string _ownerid_value { get; set; }
        public DateTime sim_qtd_oportunidade_ganhas_date { get; set; }
        public DateTime sim_qtd_oportunidade_perdidas_date { get; set; }
        public int customersizecode { get; set; }
        public string _sim_proprietario_anterior_value { get; set; }
        public DateTime sim_total_contratos_date { get; set; }
        public bool bz_conta_mapeada { get; set; }
        public DateTime openrevenue_date { get; set; }
        public double openrevenue_base { get; set; }
        public int businesstypecode { get; set; }
        public bool donotemail { get; set; }
        public double sim_faturamento_mps_acum_base { get; set; }
        public string address1_addressid { get; set; }
        public bool msdyn_gdproptout { get; set; }
        public int address2_freighttermscode { get; set; }
        public int statuscode { get; set; }
        public DateTime createdon { get; set; }
        public int opendeals_state { get; set; }
        public int sim_faturamento_pcs_acum_state { get; set; }
        public bool sim_flagreserva { get; set; }
        public double sim_faturamento_mobile_acum { get; set; }
        public double openrevenue { get; set; }
        public int sim_qtd_oportunidade_perdidas { get; set; }
        public bool sim_revenda_ativa { get; set; }
        public bool donotfax { get; set; }
        public int sim_qtd_oportunidade_perdidas_state { get; set; }
        public bool donotbulkpostalmail { get; set; }
        public bool donotsendmm { get; set; }
        public int versionnumber { get; set; }
        public int sim_total_equipamentos_state { get; set; }
        public bool creditonhold { get; set; }
        public DateTime sim_faturamento_mobile_acum_date { get; set; }
        public DateTime sim_qtd_equip_date { get; set; }
        public string _transactioncurrencyid_value { get; set; }
        public double sim_total_equipamentos { get; set; }
        public int sim_qtd_oportunidade_ganhas { get; set; }
        public string sim_fim { get; set; }
        public bool donotbulkemail { get; set; }
        public int sim_qtd_oporunidades_state { get; set; }
        public DateTime sim_faturamento_inov_acum_date { get; set; }
        public bool sim_conta_decisoria { get; set; }
        public string _modifiedby_value { get; set; }
        public bool followemail { get; set; }
        public int shippingmethodcode { get; set; }
        public string _createdby_value { get; set; }
        public DateTime sim_faturamento_mps_acum_date { get; set; }
        public DateTime sim_total_equipamentos_date { get; set; }
        public int territorycode { get; set; }
        public string accountid { get; set; }
        public double sim_faturamento_pcs_acum { get; set; }
        public double sim_faturamento_inov_acum { get; set; }
        public double sim_faturamento_pcs_acum_base { get; set; }
        public int sim_total_contratos_state { get; set; }
        public bool bz_flaggcnacarteiraenviaemailaviso { get; set; }
        public bool participatesinworkflow { get; set; }
        public int accountclassificationcode { get; set; }
        public double sim_faturamento_mobile_acum_base { get; set; }
        public string address2_addressid { get; set; }
        public bool sim_conta_grupo_economico { get; set; }
        public DateTime sim_faturamento_pcs_acum_date { get; set; }
        public bool sim_status_qualificacao { get; set; }
        public DateTime opendeals_date { get; set; }
        public string telephone3 { get; set; }
        public string bz_status_atualizacao_cortex { get; set; }
        public string address1_shippingmethodcode { get; set; }
        public string sharesoutstanding { get; set; }
        public string sim_acumulado_pcsnotes { get; set; }
        public string ownershipcode { get; set; }
        public string _defaultpricelevelid_value { get; set; }
        public string _preferredequipmentid_value { get; set; }
        public string address1_freighttermscode { get; set; }
        public string bz_capital_social { get; set; }
        public string sim_contribuinteicms { get; set; }
        public string address1_upszone { get; set; }
        public string sim_num_contrato { get; set; }
        public string websiteurl { get; set; }
        public string bz_data_inclusao_gc_carteira { get; set; }
        public string address2_city { get; set; }
        public string _slainvokedid_value { get; set; }
        public string address1_postofficebox { get; set; }
        public string importsequencenumber { get; set; }
        public string preferredappointmentdaycode { get; set; }
        public string customertypecode { get; set; }
        public string utcconversiontimezonecode { get; set; }
        public string overriddencreatedon { get; set; }
        public string aging90 { get; set; }
        public string stageid { get; set; }
        public string sim_tamanho_conta { get; set; }
        public string bz_total_color { get; set; }
        public string address1_latitude { get; set; }
        public string address1_utcoffset { get; set; }
        public string bz_ranking_similaridade { get; set; }
        public string _msdyn_accountkpiid_value { get; set; }
        public string sim_canal_atendimento { get; set; }
        public string _masterid_value { get; set; }
        public string _sim_ramo_atividade_value { get; set; }
        public string sim_zona { get; set; }
        public string lastonholdtime { get; set; }
        public string sim_grupo_economico { get; set; }
        public string address2_fax { get; set; }
        public string _sim_segmento_value { get; set; }
        public string sim_tot_opp_geradas { get; set; }
        public string sim_qtd_oportunidade_ativas { get; set; }
        public string accountnumber { get; set; }
        public string bz_vlr_equip { get; set; }
        public string address2_line1 { get; set; }
        public string sim_venc_contrato_pc { get; set; }
        public string address1_telephone3 { get; set; }
        public string address1_telephone2 { get; set; }
        public string sim_descrio_cnae { get; set; }
        public string address1_telephone1 { get; set; }
        public string sim_num_funcionario { get; set; }
        public string sim_tot_opp_ganhas { get; set; }
        public string address2_postofficebox { get; set; }
        public string sim_acumulado_mobile { get; set; }
        public string stg_inscricaoestadual { get; set; }
        public string _primarycontactid_value { get; set; }
        public string emailaddress1 { get; set; }
        public string ftpsiteurl { get; set; }
        public string emailaddress2 { get; set; }
        public string address2_latitude { get; set; }
        public string processid { get; set; }
        public string emailaddress3 { get; set; }
        public string address2_composite { get; set; }
        public string _sim_marca_pc_value { get; set; }
        public string bz_total_geral_qualificacao { get; set; }
        public string traversedpath { get; set; }
        public string address1_city { get; set; }
        public string _sim_cnae_value { get; set; }
        public string sim_qtd_equipamento_pc { get; set; }
        public string sim_faturamento_estimado_termica_coletores_base { get; set; }
        public string sim_tot_opp_ativas { get; set; }
        public string address2_line2 { get; set; }
        public string aging30_base { get; set; }
        public string stg_nomefantasia { get; set; }
        public string numberofemployees { get; set; }
        public string sim_qtd_equipamento_termica { get; set; }
        public string teamsfollowed { get; set; }
        public string address1_addresstypecode { get; set; }
        public string address2_stateorprovince { get; set; }
        public string new_tamanho_conta { get; set; }
        public string address2_postalcode { get; set; }
        public string entityimage_url { get; set; }
        public string address1_composite { get; set; }
        public string aging60 { get; set; }
        public string stg_cnpj { get; set; }
        public string sim_venc_contrato_mobile { get; set; }
        public string _sim_cliente_potencial_value { get; set; }
        public string timezoneruleversionnumber { get; set; }
        public string new_filiais_txt { get; set; }
        public string address2_telephone3 { get; set; }
        public string address2_telephone2 { get; set; }
        public string address2_telephone1 { get; set; }
        public string address2_upszone { get; set; }
        public string address1_postalcode { get; set; }
        public string _owningteam_value { get; set; }
        public string sim_vol_total_impressao { get; set; }
        public string sim_complemento { get; set; }
        public string primarysatoriid { get; set; }
        public string address2_line3 { get; set; }
        public string new_motivo_semperfil { get; set; }
        public string timespentbymeonemailandmeetings { get; set; }
        public string sim_flag_encerramento { get; set; }
        public string address1_country { get; set; }
        public string sim_zoneamento { get; set; }
        public string bz_vlr_pb { get; set; }
        public string address2_longitude { get; set; }
        public string _modifiedonbehalfby_value { get; set; }
        public string sim_numcep { get; set; }
        public string _sim_marca_mobile_value { get; set; }
        public string revenue_base { get; set; }
        public string creditlimit { get; set; }
        public string sim_razao_status_aux { get; set; }
        public string _sim_marca_termica_value { get; set; }
        public string sim_faturamento_estimado_termica_coletores { get; set; }
        public string address1_line2 { get; set; }
        public string paymenttermscode { get; set; }
        public string address1_county { get; set; }
        public string sim_tamanho_conta_faturamento_base { get; set; }
        public string _territoryid_value { get; set; }
        public string bz_dataflagverificacaogcflow { get; set; }
        public string _preferredsystemuserid_value { get; set; }
        public string marketcap { get; set; }
        public string sim_acumulado_inovdigital_base { get; set; }
        public string preferredappointmenttimecode { get; set; }
        public string address1_fax { get; set; }
        public string sim_qtd_equipamento_mobile { get; set; }
        public string _sim_fornecedor_termicas_coletores_value { get; set; }
        public string _createdonbehalfby_value { get; set; }
        public string sim_venc_contrato_termica { get; set; }
        public string _sim_filial_value { get; set; }
        public string address2_name { get; set; }
        public string _sim_fornecedor_mobile_value { get; set; }
        public string creditlimit_base { get; set; }
        public string marketcap_base { get; set; }
        public string _modifiedbyexternalparty_value { get; set; }
        public string address2_utcoffset { get; set; }
        public string sim_origem_lead { get; set; }
        public string _originatingleadid_value { get; set; }
        public string sim_acumulado_mps { get; set; }
        public string sic { get; set; }
        public string bz_porte_cnpj { get; set; }
        public string _preferredserviceid_value { get; set; }
        public string _slaid_value { get; set; }
        public string fax { get; set; }
        public string sim_flag_cancelamento { get; set; }
        public string address1_line1 { get; set; }
        public string sim_faturamento_estimado_mobile_base { get; set; }
        public string sim_matriz_filial { get; set; }
        public string address2_county { get; set; }
        public string sim_tot_opp_perdidas { get; set; }
        public string bz_total_geral_qualificacao_base { get; set; }
        public string sim_venc_contrato_mps { get; set; }
        public string sim_chave_conta { get; set; }
        public string new_observacao_marca { get; set; }
        public string aging30 { get; set; }
        public string sim_faturamento_estimado_mps { get; set; }
        public string address1_line3 { get; set; }
        public string sim_tamanho_crm40 { get; set; }
        public string bz_capital_social_base { get; set; }
        public string bz_total_pb { get; set; }
        public string _sim_gerente_comercial_value { get; set; }
        public string industrycode { get; set; }
        public string address1_stateorprovince { get; set; }
        public string sim_qtd_filiais { get; set; }
        public string sim_acumulado_mps_base { get; set; }
        public string sim_razao_qualificao { get; set; }
        public string _sim_nome_revenda_value { get; set; }
        public string sim_num_opp_ganhas { get; set; }
        public string sim_tamanho_conta_faturamento { get; set; }
        public string sim_faturamento_estimado_mobile { get; set; }
        public string onholdtime { get; set; }
        public string _createdbyexternalparty_value { get; set; }
        public string entityimage_timestamp { get; set; }
        public string new_observacao_qualifica { get; set; }
        public string entityimageid { get; set; }
        public string sim_faturamento_estimado_mps_base { get; set; }
        public string _parentaccountid_value { get; set; }
        public string sim_acumulado_inovdigital { get; set; }
        public string bz_apelido { get; set; }
        public string sim_num_func { get; set; }
        public string yominame { get; set; }
        public string lastusedincampaign { get; set; }
        public string bz_contribuinte_icms { get; set; }
        public string sim_faturamento_estimado_pc_notebook_base { get; set; }
        public string accountcategorycode { get; set; }
        public string primarytwitterid { get; set; }
        public string _sim_fornecedor_pc_notebook_value { get; set; }
        public string telephone2 { get; set; }
        public string stockexchange { get; set; }
        public string revenue { get; set; }
        public string description { get; set; }
        public string bz_qtd_equip { get; set; }
        public string sim_acumulado_pcsnotes_base { get; set; }
        public string bz_vlr_color_base { get; set; }
        public string sim_faturamento_estimado_pc_notebook { get; set; }
        public string bz_status_cnpj { get; set; }
        public string bz_vlr_color { get; set; }
        public string aging90_base { get; set; }
        public string tickersymbol { get; set; }
        public string bz_dt_atulizacao_qualificacoes { get; set; }
        public string _sim_subsegmento_value { get; set; }
        public string sim_num_opp_ativas { get; set; }
        public string sim_reserva_ate { get; set; }
        public string sim_conta_qualificada { get; set; }
        public string address1_name { get; set; }
        public string telephone1 { get; set; }
        public string bz_vlr_pb_base { get; set; }
        public string sim_tipo_conta { get; set; }
        public string _sim_grupo_economico_lkp_value { get; set; }
        public string address1_primarycontactname { get; set; }
        public string address1_longitude { get; set; }
        public string address2_primarycontactname { get; set; }
        public string entityimage { get; set; }
        public string bz_data_atualizacao_cortex { get; set; }
        public string bz_diasgcnacarteira { get; set; }
        public string sim_destino_conta { get; set; }
        public string sim_acumulado_mobile_base { get; set; }
        public string aging60_base { get; set; }
        public string bz_vlr_equip_base { get; set; }
        public string address2_country { get; set; }
    }
}
